# Generated by Django 3.2.8 on 2021-10-30 02:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0002_auto_20211019_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item_list',
        ),
        migrations.AddField(
            model_name='listitem',
            name='user_id',
            field=models.ForeignKey(default=datetime.date, on_delete=django.db.models.deletion.CASCADE, to='toDoList.user'),
            preserve_default=False,
        ),
    ]
